# Generated by Django 5.1.6 on 2025-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='customer_register_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=50)),
                ('days', models.CharField(max_length=50)),
                ('pickup_date', models.CharField(max_length=50)),
                ('drop_date', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('current_address', models.CharField(max_length=500)),
                ('permanent_address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=10)),
                ('booking_number', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('alternative_number', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=50)),
                ('licence_type', models.CharField(max_length=20)),
                ('licence_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customer_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('booking_number', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=50)),
            ],
        ),
    ]
